"""
executor.py
-----------
The "code interpreter" of Open Julius.

It runs Python code (generated by the Gemini agent) inside a persistent,
per-session namespace and captures three things:

  1. stdout / stderr  (text the code prints)
  2. matplotlib figures (returned as base64 PNG images -> charts)
  3. any error traceback (so the agent can self-correct)

This mirrors how Julius AI executes generated Python in a sandbox and
surfaces the resulting tables and visualizations.
"""

import io
import base64
import contextlib
import traceback

# Use a non-interactive backend so charts render without a display server.
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

# Limit how much text we keep, to control memory + LLM token usage.
MAX_OUTPUT_CHARS = 12000


def build_namespace():
    """Create a fresh execution namespace pre-loaded with common libraries.

    Variables defined by the model persist in this dict across turns,
    which lets the agent build on earlier results (just like a notebook).
    """
    import pandas as pd
    import numpy as np

    namespace = {
        "__name__": "__main__",
        "pd": pd,
        "np": np,
        "plt": plt,
    }

    # seaborn is optional-but-nice; import lazily so a missing install
    # never breaks the whole environment.
    try:
        import seaborn as sns
        namespace["sns"] = sns
        sns.set_theme(style="whitegrid")
    except Exception:
        pass

    return namespace


def _truncate(text: str) -> str:
    if text and len(text) > MAX_OUTPUT_CHARS:
        return text[:MAX_OUTPUT_CHARS] + "\n... [output truncated]"
    return text


def execute_code(code: str, namespace: dict) -> dict:
    """Execute `code` within `namespace`.

    Returns a dict:
        {
          "stdout": str,          # captured prints
          "charts": [base64 png], # any matplotlib figures created
          "error":  str | None,   # traceback if execution failed
        }
    """
    stdout_buffer = io.StringIO()
    charts = []
    error = None

    # Start from a clean figure state so we only capture charts
    # produced by *this* execution.
    plt.close("all")

    try:
        with contextlib.redirect_stdout(stdout_buffer), \
                contextlib.redirect_stderr(stdout_buffer):
            exec(code, namespace)

        # Capture every figure the code created.
        for fig_num in plt.get_fignums():
            fig = plt.figure(fig_num)
            buf = io.BytesIO()
            try:
                fig.savefig(buf, format="png", bbox_inches="tight", dpi=110)
                buf.seek(0)
                charts.append(base64.b64encode(buf.read()).decode("utf-8"))
            finally:
                buf.close()
        plt.close("all")

    except Exception:
        error = traceback.format_exc(limit=6)
        plt.close("all")

    return {
        "stdout": _truncate(stdout_buffer.getvalue()),
        "charts": charts,
        "error": _truncate(error) if error else None,
    }
